# Seata 客户端配置
client {
    application-id = waimai-backend
    transaction-service-group = waimai_tx_group
}

service {
    vgroup-mapping.waimai_tx_group = default
    default.grouplist = 127.0.0.1:8091
    enableDegrade = false
    disableGlobalTransaction = false
}
