-- MySQL 从库初始化
-- 创建分片数据库
CREATE DATABASE IF NOT EXISTS waimai_ds0 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS waimai_ds1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS waimai_ds2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS waimai_ds3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 配置主从复制（需在容器内手动执行 CHANGE MASTER TO）
-- CHANGE MASTER TO MASTER_HOST='mysql', MASTER_USER='root', MASTER_PASSWORD='123456', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=0;
-- START SLAVE;
